### ISSUE TITLE
Bug: Missing kid in the header

### ISSUE THREAD

**Issue by cre8** [openwallet-foundation-labs/sd-jwt-js#104]
Right now we have only the reference to the issuer in either the `iss` or `issuer` field. But to determine the used key, we need to place a reference into the header

**Comment by lukasjhan** [comment]
I guess we need to pass not only `alg` but also `kid` to the verifier function.

**Comment by cre8** [comment]
I saw that the user can pass it via the option handler in the issue call. Looking here:
https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-01.html#section-3.5-2.2

In case the `iss` is a DID, it should already include the key reference. There is not forced to set the kid since in case of a did the key resolution is defined. But it's not clear what happens when both is defined.

**Comment by cre8** [comment]
Since the kid can manually be set in the header, we can ignore this here. It is up the issuer set the correct kid that is matching with the issuer reference
