### ISSUE TITLE
Discussion: presentation definition as object and not only sting list

### ISSUE THREAD

**Issue by cre8** [openwallet-foundation-labs/sd-jwt-js#132]
Right now a presentation request is defined like `['name', 'address.city', 'address.street']` defining the fields that should be disclosed. The equivalent object oriented presentation looks like this:
```
const obj = {
      name: true,
      address: {
        city: true,
        street: true,
};
```

However I have some concerns allowing the object oriented approach:
- adding types to a definition is a unnecessary feature. It it's set to true, it should be disclosed. If it's not present, it should not. So we don't even have a use case to set value to false
- Disclosing array elements is not possible. With the object oriented way I can not create the case like `[names.2.value]`.

Because of this I suggest to only allow the list presentation approach and not add or replace it with the object one.

**Comment by lukasjhan** [comment]
FYI: we could implement both, and I think it would be easier to convert object method to string method. :)

**Comment by lukasjhan** [comment]
> Disclosing array elements is not possible. With the object oriented way I can not create the case like [names.2.value]

Maybe we could do it like:

```
{
  name: {
    0: {
      value: true
     }
  }
}
```

**Comment by cre8** [comment]
After digging deeper I find no perfect usage of the object oriented way:

We are only accepting one value, so the type of the object could be defined like:
```
export type InputObject = {
  [key: string]: true | InputObject;
};
```
However this will fail since when you create the obj without a type, it will set the type of
```
const obj = {
  name: true
}
```
Name to boolean and not true. This only happens when we pass the type during init like `const obj: InputObject`. However this could lead to confusion under developers, so we have to set type to boolean.
But then the developer could think "do I need to include all values and set them to false when I do not want to disclosure them?" Since he does not no if we check with typeof !== undefined what is the behaviour if a variable is not set.

Another approach of types based objects would be like:
```
    const value = {
      name: 'Mark',
      address: {
        city: 'New York',
        street: '5th Avenue',
      },
    };

    type ValueType = typeof value;

    const obj: InputObject<keyof ValueType> = {
      name: true,
      address: {
        city: true,
        street: true,
      },
      list: {
        0: true,
      },
      elements: {
        0: {
          name: true,
        },
      },
    };
    
/**
 * Represtens the structure of the disclosure schema
 */
export type InputObject<T extends string = string> = {
  [K in T]?: boolean | InputObject<T>;
};    
```

However here we can not pass the nested types for the validation


So for me the `["address.name"] approach is the best one, where we point to the field. Compared to the current approach `["address", "address.name"]` and `["address.name"]` become redundant since we have all the required information in the short form

**Comment by lukasjhan** [comment]
I found a confusing example of object approach.
Here is an example:

```js
const claim = {
  firstname: "lukas",
  address: {  // address will be set SD 
    city: "seoul",
    country: "south korea"
  }
}
```

So I set disclosureFrame like this:

```js
{
  _sd: ["address"]
}
```

Then If I want to present `address`,
Should I use

```js
{
   address: true
}
```

or 

```js
{
  address: {
     city: true,
     country: true,
  }
}
```

I think It's very confusing.

**Comment by cre8** [comment]
I think in that case it would be:
```
{
   address: true
}
```
like: "all sub values will be disclosed"

**Comment by lukasjhan** [comment]
I can make a sample PR today base on @cre8 works and let's talk more with the PR.

**Comment by lukasjhan** [comment]
I opened it in #138

**Comment by cre8** [comment]
We went with the frame approach, closing this
