### ISSUE TITLE
Disclosure digest should be accessible without providing Hasher

### ISSUE THREAD

**Issue by c2bo** [openwallet-foundation-labs/sd-jwt-js#150]
For a holder, you receive the Disclosures with digests and right now can't easily access the digests of disclosures (private member). The only way to access a digest, is via calling `digest` which requires a HaserAndAlg as input
```typescript
  public async digest(hash: HasherAndAlg): Promise<string> {
    const { hasher, alg } = hash;
    if (!this._digest) {
      const hash = await hasher(this.encode(), alg);
      this._digest = Uint8ArrayToBase64Url(hash);
    }
    return this._digest;
  }
```

I do think it would be beneficial to make either the variable directly accessible (public) or change the signature of the function to have `hash` as an optional argument as it is only used when computing a new digest.

**Comment by lukasjhan** [comment]
Hi @c2bo. That's a really good suggestion. I too am having difficulty implementing a feature in PEX.
I think we should make them public.
