### ISSUE TITLE
Some of features in decode, present package change the input object.

### ISSUE THREAD

**Issue by lukasjhan** [openwallet-foundation-labs/sd-jwt-js#163]
What I found out while implementing PEX is that there are functions that directly modify objects received as input. I think this will confuse users, so I think I'll have to copy the object internally and use it.

I proposed:

-  use after deep clone inside

selectDisclosures in @sd-jwt/present

- comments or write a docs that this function change the input.

unpack, unpackSync, unpackObj and unpackArray in @sd-jwt/decode

**Comment by lukasjhan** [comment]
@cre8 What do you think about it? If you think it's good, I'll make a PR today :)

**Comment by cre8** [comment]
@lukasjhan I think this is a good idea to avoid side effects.
