### ISSUE TITLE
Fix biome for `Do not export from a test file.`

### ISSUE THREAD

**Issue by lukasjhan** [openwallet-foundation-labs/sd-jwt-js#206]
https://github.com/openwallet-foundation-labs/sd-jwt-js/actions/runs/8690319445/job/23830019035?pr=204#step:6:24

I think It happends after biome version upgrade.

**Comment by cre8** [comment]
yeah, they added this rule, see: https://biomejs.dev/linter/rules/no-exports-in-test/#:~:text=If%20you%20import%20from%20a,to%20be%20shared%20across%20tests.
