### ISSUE TITLE
Fix test CI for nodejs 16

### ISSUE THREAD

**Issue by lukasjhan** [openwallet-foundation-labs/sd-jwt-js#207]
Looks like new pnpm has version limit.

check here: https://github.com/openwallet-foundation-labs/sd-jwt-js/actions/runs/8707141840/job/23959522487#step:5:72

Maybe we need to use older pnpm to run the old version node tests

**Comment by lukasjhan** [comment]
#204 #205 failed due to this issue. and PRs coming up in the future will also fail.

**Comment by lukasjhan** [comment]
https://github.com/pnpm/pnpm/releases/tag/v9.0.0

**Comment by lukasjhan** [comment]
Hi @cre8, Please check if the direction I corrected is okay. It also related with #206

**Comment by cre8** [comment]
@lukasjhan based on the end of life information, I would suggest to drop support for version 16 instead of limiting the pnpm version not to be the latest version, see: https://endoflife.date/nodejs
