### ISSUE TITLE
Bug: broken ci

### ISSUE THREAD

**Issue by cre8** [openwallet-foundation-labs/sd-jwt-js#213]
the publish task will fail, it seems the lock file is generated and lerna does not like uncommited changes.

I will try to find the reason why it's generated, "dirty fix" would be to ignore uncommited changes when lerna is running.

**Comment by lukasjhan** [comment]
I think it's due to the new version of pnpm. When I use `pnpm install` with pnpm version 9.0.6. it reproduce the whole lockfile.
I opened a PR for add `--frozen-lockfile` in #216

**Comment by lukasjhan** [comment]
So I think there are two option. 

1. add `--frozen-lockfile` in ci command.
2. commit new lockfile from new version of pnpm
3. or both
