### ISSUE TITLE
pass Accept header `application/statuslist+jwt` in status list fetcher

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation-labs/sd-jwt-js#234]
As it is expected that the status list in this format (the spec defines four formats): https://www.ietf.org/archive/id/draft-ietf-oauth-status-list-02.html#name-status-list-request

**Comment by cre8** [comment]
I agree. We should set it as a default one and not the typical `application/json`. From my point of view it's fine to just fine to implement it in the default fetcher. There is no need that the user can pass it as a parameter and then the SDK is performing the correct request.
