### ISSUE TITLE
e2e test not included

### ISSUE THREAD

**Issue by lukasjhan** [openwallet-foundation-labs/sd-jwt-js#76]
in vitest.shared.js e2e test file is excluded.
Removing exclude value lead to activate e2e test

```
import { defineProject, mergeConfig } from 'vitest/config';
export const browserConfig = defineProject({
  test: {
    globals: true,
    coverage: {
      exclude: ['examples/**'],
      reporter: ['json'],
    },
    environment: 'jsdom',
  },
});

export const nodeConfig = defineProject({
  test: {
    globals: true,
    coverage: {
      //TODO: the exclude is not working, therefore the coverage result are not correct.
      exclude: ['examples/**'],
      reporter: ['json'],
    },
    environment: 'node',
  },
});

export const allEnvs = mergeConfig(browserConfig, nodeConfig);

```

@cre8 Please share your thoughts :)

**Comment by cre8** [comment]
I think I wanted to separate unit tests and e2e tests in the first place. But I am fine running them together :D

Speaking of tests, do we need to run it on different node versions? You can use the matrix feature in GitHub to do so.

**Comment by lukasjhan** [comment]
Let's just test them together. :) It's few cases 
Running it on different node versions is good idea. I think we need to test it in node 16,18, and 20
