### ISSUE TITLE
Fix Test coverage 

### ISSUE THREAD

**Issue by lukasjhan** [openwallet-foundation-labs/sd-jwt-js#78]
coverage.exclude is not working in vitest.shared.js

https://vitest.dev/config/#coverage-exclude

**Comment by lukasjhan** [comment]
It's in the docs but not working. Maybe we need to find workaround

**Comment by cre8** [comment]
@lukasjhan I think it's because of the monorepo approach, see: https://vitest.dev/guide/workspace#coverage

**Comment by lukasjhan** [comment]
@cre8 Thank you for checking :D
