### ISSUE TITLE
Remove any usage

### ISSUE THREAD

**Issue by cre8** [openwallet-foundation-labs/sd-jwt-js#79]
To remove the `noExplicitAny` rule from biome, we need to update the code: https://github.com/openwallet-foundation-labs/sd-jwt-js/blob/main/biome.json#L25

**Comment by cre8** [comment]
@berendsliedrecht your fix will break the tests when I want to include the e2e.spec.ts ones.
```
 FAIL  |core| test/app-e2e.spec.ts > App > From JSON (array_data_types)

 FAIL  |core| test/app-e2e.spec.ts > App > From JSON (array_data_types)
 FAIL  |core| test/app-e2e.spec.ts > App > From JSON (array_of_nulls)
TypeError: Cannot destructure property '_sd' of '_a' as it is null.
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/3]⎯

 FAIL  |core| test/app-e2e.spec.ts > App > From JSON (object_data_types)
TypeError: Cannot destructure property '_sd' of '_a' as it is null.
```

**Comment by lukasjhan** [comment]
I'm also look into it. the `null` value is problem.

**Comment by berendsliedrecht** [comment]
Is the linting not applied to the test files? We should def add that, maybe with less strict rules though.

**Comment by lukasjhan** [comment]
@berendsliedrecht It's not about lint, the test logic is failed. Looks like code crash handling `null`

**Comment by lukasjhan** [comment]
I'll change it to `if (typeof obj === 'object' && obj !== null)`

**Comment by cre8** [comment]
I excluded e2e.spec when using vitest in the first place because I thought we should run the test types in different runs.

**Comment by lukasjhan** [comment]
Since it does not currently run in CI, I think it would be a good idea to include it first. @cre8

**Comment by cre8** [comment]
I will make a PR based on the main branch to include the e2e tests.
