### ISSUE TITLE
Change default branch to next

### ISSUE THREAD

**Issue by cre8** [openwallet-foundation-labs/sd-jwt-js#91]
To be aligned with the new publish strategy in #89 we need to change the default branch from main to next

@ryjones can you do this for us please, we do not have the privileges for this action? :)

**Comment by lukasjhan** [comment]
done with #89. Thank you guys :)

**Comment by cre8** [comment]
@lukasjhan because we didn't install the app: https://github.com/apps/settings can you do this? I am not in the lab, can you request this? Or @ryjones ?

**Comment by lukasjhan** [comment]
I requested :)

**Comment by lukasjhan** [comment]
@cre8 I'll request an invitation to the lab org. 
The app is set but, it seems not working.

**Comment by lukasjhan** [comment]
@ryjones did manually.
